version: "3.7"
services:
  db:
    image: "postgres:latest"
    container_name: "my_postgres"
    restart: always
    ports:
      - "54320:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: postgres 
  go:
    build: .
    container_name: my-running-go-app
    ports:
      - "8080:8080"
    volumes:
      - ".:/go/src/app"